config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    has_one_attached :image
    validates :image, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..2.megabytes }
    
    def tag_list
        self.tags.collect do |tag|
          tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end

    def count_view
        self.update_attribute(:views, self.views+=1)
    end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :author_name, :body, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper

    before_action :require_login, except: [:index, :show]

    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
        @article.count_view
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end
    
    def create
        @article = Article.new(article_params)
        if @article.save
          flash[:success] = "Article successfully created"
          redirect_to @article
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])
        if @article.update_attributes(article_params)
          flash[:success] = "Article was successfully updated"
          redirect_to @article
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end


    def destroy
        @article = Article.find(params[:id])
        @image = @article.image
        if @image.nil?
            @image.purge_later
        end
        if @article.destroy
            flash[:success] = 'Article was successfully deleted.'
            redirect_to articles_url
        else
            flash[:error] = 'Something went wrong'
            redirect_to articles_url
        end
    end
    

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
    def new
    end
  
    def create
      if login(params[:email], params[:password])
        redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
      else
        flash.now.alert = "Login failed."
        render action: :new
      end
    end
  
    def destroy
      logout
      redirect_to(:authors, notice: 'Logged out!')
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include CommentsHelper

    before_action :require_login, except: [:create]

    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]
        if @comment.save
          flash[:success] = "Comment successfully created"
          redirect_to article_path(@comment.article)
        else
          flash[:error] = "Something went wrong"
          redirect_to article_path(params[:article_id], @comment)
        end
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :require_login, only: [:destroy]

    def index
        @tags = Tag.all
    end
    
    def show
        @tag = Tag.find(params[:id])
    end

    def destroy
        @tag = Tag.find(params[:id])
        if @tag.destroy
            flash[:success] = 'Tag was successfully deleted.'
            redirect_to tags_url
        else
            flash[:error] = 'Something went wrong'
            redirect_to tags_url
        end
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    private
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
    
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    private
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h5>Comment by <%= comment.author_name %></h5>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="input-field"> 
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="input-field"> 
    <%= f.label :body %><br />
    <%= f.text_area :body, class: "materialize-textarea" %>
  </div>
  <div class="input-field"> 
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </div>
  <% unless @article.image.blank? %>
      <%= image_tag @article.image.variant(resize: "300x300") %><br/>
  <% end %>
  <div> 
    <div class="file-field input-field">
      <div class="btn red">
      <span>Upload Image</span>
      <%= f.file_field :image%>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>
  <br />
  <div> 
    <%= f.submit "Submit", class: "btn red"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<div class="collection">
  <% @articles.each do |article| %>
    <div class="collection-item">
      <%= link_to article.title, article_path(article) %>
      <%= "views (#{article.views})" %>
    </div>
  <% end %>
</div>

<% if logged_in? %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
 <% unless @article.image.blank? %>
      <%= image_tag @article.image.variant(resize: "300x300") %><br/>
<% end %>
<div class="card-panel red">
  <span class="white-text">
    <%= @article.body %>
  </span>
</div>

<% if logged_in? %>
  <p><%= link_to "Delete", article_path(@article), method: :delete , data: {confirm: "Do you really want to delete the article?"}%></p>
  <p><%= link_to "Edit", edit_article_path(@article) %></p>
<% end %>
<%= link_to "Back", articles_path %>
<%= render partial: 'comments/form' %>
<h4>Comments (<%= @article.comments.size %>)</h4>
<%= render partial: 'articles/comment', collection: @article.comments %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="input-field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="input-field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn red" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="input-field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="input-field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="input-field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit 'Submit', class: "btn red" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table class="table-responsive striped centered">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h4>Post a Comment</h4>
<%= form_for [ @article, @comment ] do |f| %>
  <div class="input-field"> 
    <%= f.label :author_name, "Your Name"  %>
    <%= f.text_field :author_name %>
  </div>
  <div class="input-field"> 
    <%= f.label :body, "Content" %><br/>
    <%= f.text_area :body, class: "materialize-textarea"%>
  </div>
  <div>
    <%= f.submit 'Submit', class: "btn red" %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer black">
<div class="footer-content"> 
    <% if logged_in? %>
        <%= "Logged in as #{current_user.email}" %>
        <%= link_to "logout", logout_path, class: "btn red" %>
    <% else %>
        <%= link_to "login", login_path, class: "btn blue" %>
    <% end %>
</div>
<div class="footer-copyright">
    <div class="container">
    © 2019 Nicolás Nisoria
    </div>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :h5, value, class: "flash" %>
    <% end %>
    <div id="container">
      <div id="content">
      
        <%= yield %>
        <br>
        <br>
      </div>
      
      <%= render partial: 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
      <% if logged_in? %>
        <p><%= link_to "delete", tag_path(tag), method: :delete , data: {confirm: "Do you really want to delete the tag?"}%></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>